Repository paketo-buildpacks/gradle, pull requests merged in 2022-08, with the labels that each got.

#166 Update Pipeline to 1.25.2
  .github/pipeline-version
  .github/workflows/pb-create-package.yml
  .github/workflows/pb-minimal-labels.yml
  .github/workflows/pb-synchronize-labels.yml
  .github/workflows/pb-tests.yml
  .github/workflows/pb-update-draft-release.yml
  .github/workflows/pb-update-go.yml
  .github/workflows/pb-update-gradle.yml
  .github/workflows/pb-update-pipeline.yml
Labels: type:task, semver:patch

#167 Bump go.mod dependencies
  go.mod
  go.sum
Labels: semver:patch, type:dependency-upgrade

#171 Allow setting a gradle init script via an env var
  README.md
  buildpack.toml
  gradle/build.go
  gradle/build_test.go
Labels: semver:minor, type:enhancement

#177 Implement RFC 0050: Rename Buildpack
  README.md
  buildpack.toml
Labels: type:task, semver:patch
